import json

nb = {
  "cells": [
    {
      "cell_type": "markdown",
      "id": "a1b2c3d4",
      "metadata": {},
      "source": [
        "# Detection Pipeline (PKU-MMD / TSU) — Kaggle\n",
        "\n",
        "**Chiến lược I/O tối ưu cho đa luồng trên Kaggle:**\n",
        "- **Đọc video/annotation:** Streaming trực tiếp qua `rclone mount` từ Google Drive\n",
        "- **Ghi output (jsonl, failed_frames):** Ra `/kaggle/working/` (local SSD, I/O nhanh nhất)\n",
        "- **Sync kết quả:** Dùng `rclone copy` lên Drive 1 lần khi xong\n",
        "\n",
        "> ⚠️ **Lưu ý Kaggle:**\n",
        "> - Mỗi session Kaggle giới hạn **12 tiếng** (GPU T4 x2 hoặc P100).\n",
        "> - `/kaggle/working/` giới hạn **20 GB** disk space — đủ cho output jsonl.\n",
        "> - Internet access phải **BẬT** trong Kaggle Settings để clone repo và mount Drive.\n",
        "> - rclone **chưa có sẵn** trên Kaggle, phải cài thủ công (Cell 2).\n",
        "\n",
        "**Thứ tự chạy:** Cell 1 → 2 → 3 → 4 → 5 → 6 → 7 → 8 → 9 (sync)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "b1c2d3e4",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 1: Lay code moi nhat tu GitHub\n",
        "import os\n",
        "REPO   = \"https://github.com/tuan8p/Skeleton-EAA-Pose.git\"\n",
        "BRANCH = \"dai\"\n",
        "WORKDIR = \"/kaggle/working/Skeleton-EAA-Pose\"\n",
        "if not os.path.isdir(WORKDIR):\n",
        "    !git clone -b {BRANCH} {REPO} {WORKDIR}\n",
        "else:\n",
        "    !git -C {WORKDIR} pull origin {BRANCH}\n",
        "%cd {WORKDIR}"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "c2d3e4f5",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 2: Cai dat thu vien + rclone\n",
        "# Cai rclone (Kaggle chua co san, phai cai thu cong)\n",
        "!curl https://rclone.org/install.sh | bash 2>/dev/null || true\n",
        "!which rclone && rclone version\n",
        "\n",
        "# Cai thu vien Python\n",
        "!pip install -q -r requirements.txt"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "d3e4f5g6",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 3: Cau hinh rclone token va Mount Google Drive\n",
        "# ============================================================\n",
        "# Kaggle dung headless auth (khong co browser trong session):\n",
        "#\n",
        "# BUOC 1 (lam 1 lan tren may tinh co browser):\n",
        "#   rclone authorize \"drive\"\n",
        "#   => Copy toan bo token JSON ra\n",
        "#\n",
        "# BUOC 2: Paste token vao Kaggle Secret voi ten 'RCLONE_TOKEN'\n",
        "#   Kaggle Settings > Add-ons > Secrets > Add Secret\n",
        "#\n",
        "# BUOC 3: Tao rclone config file tu token da luu\n",
        "# ============================================================\n",
        "\n",
        "import os, subprocess\n",
        "\n",
        "# Doc token tu Kaggle Secret (an toan hon hardcode)\n",
        "try:\n",
        "    from kaggle_secrets import UserSecretsClient\n",
        "    secrets = UserSecretsClient()\n",
        "    RCLONE_TOKEN = secrets.get_secret(\"RCLONE_TOKEN\")\n",
        "    print(\"[OK] Da doc RCLONE_TOKEN tu Kaggle Secrets\")\n",
        "except Exception:\n",
        "    # Fallback: hardcode token (chi dung khi test, KHONG commit len GitHub)\n",
        "    RCLONE_TOKEN = \"\"  # <-- Paste token JSON vao day neu khong dung Secrets\n",
        "    print(\"[WARN] Khong tim thay Kaggle Secret, dung fallback token\")\n",
        "\n",
        "# Tao file rclone.conf\n",
        "RCLONE_CONF = \"/root/.config/rclone/rclone.conf\"\n",
        "os.makedirs(os.path.dirname(RCLONE_CONF), exist_ok=True)\n",
        "with open(RCLONE_CONF, \"w\") as f:\n",
        "    f.write(f\"\"\"[gdrive]\n",
        "type = drive\n",
        "scope = drive\n",
        "token = {RCLONE_TOKEN}\n",
        "\"\"\")\n",
        "print(f\"[OK] Da tao rclone config tai: {RCLONE_CONF}\")\n",
        "\n",
        "# Mount Google Drive\n",
        "MOUNT_POINT = \"/kaggle/working/gdrive_mount\"\n",
        "os.makedirs(MOUNT_POINT, exist_ok=True)\n",
        "\n",
        "result = subprocess.run([\"mountpoint\", \"-q\", MOUNT_POINT])\n",
        "if result.returncode != 0:\n",
        "    !rclone mount gdrive: {MOUNT_POINT} \\\n",
        "        --daemon \\\n",
        "        --vfs-cache-mode full \\\n",
        "        --vfs-cache-max-size 15G \\\n",
        "        --vfs-read-ahead 512M \\\n",
        "        --transfers 8 \\\n",
        "        --buffer-size 256M \\\n",
        "        --drive-chunk-size 128M \\\n",
        "        --allow-non-empty \\\n",
        "        --log-level ERROR\n",
        "    import time; time.sleep(8)   # Kaggle can them thoi gian khoi dong rclone\n",
        "    print(f\"[OK] Da mount Google Drive tai: {MOUNT_POINT}\")\n",
        "else:\n",
        "    print(f\"[OK] Da mount san tai: {MOUNT_POINT}\")\n",
        "\n",
        "!ls {MOUNT_POINT} | head -5"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "e4f5g6h7",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 4: Cau hinh - chon dataset va duong dan\n",
        "DATASET = \"PKU\"   # \"PKU\" hoac \"TSU\"\n",
        "\n",
        "# Goc cua Google Drive (sau diem mount)\n",
        "DRIVE_ROOT = \"/kaggle/working/gdrive_mount/MyDrive\"\n",
        "\n",
        "# =======================================================\n",
        "# PATH CONFIG: chinh theo cay thu muc Google Drive cua ban\n",
        "# =======================================================\n",
        "PKU_PATHS = {\n",
        "    \"video_dir\":      f\"{DRIVE_ROOT}/ĐACN-TN_datasets/ĐATN/rawdatasets/PKUMMD/Data/RGB_VIDEO\",\n",
        "    \"annotation_dir\": f\"{DRIVE_ROOT}/ĐACN-TN_datasets/ĐATN/rawdatasets/skeletons/PKU/Label_PKUMMD_v1\",\n",
        "}\n",
        "TSU_PATHS = {\n",
        "    \"video_dir\":      f\"{DRIVE_ROOT}/ĐACN-TN_datasets/ĐATN/rawdatasets/videos/TSU\",\n",
        "    \"annotation_dir\": f\"{DRIVE_ROOT}/ĐACN-TN_datasets/ĐATN/rawdatasets/skeletons/TSU/Annotation_v1.0\",\n",
        "}\n",
        "DEPTH_PATHS = {\n",
        "    \"PKU\": f\"{DRIVE_ROOT}/PKU-MMD/DEPTH_PKUMMD\",\n",
        "    \"TSU\": f\"{DRIVE_ROOT}/TSU/videos\",\n",
        "}\n",
        "\n",
        "# Output ghi ra LOCAL /kaggle/working/ (SSD nhanh, gioi han 20GB)\n",
        "# Cuoi session se sync len Drive (Cell 9)\n",
        "LOCAL_OUTPUT = \"/kaggle/working/outputs_detection\"\n",
        "\n",
        "# Dich tren Drive de sync output len sau\n",
        "DRIVE_OUTPUT = f\"{DRIVE_ROOT}/ĐACN-TN_datasets/ĐATN/rawdatasets/outputs_detection\"\n",
        "\n",
        "# ==========================================\n",
        "# CAU HINH PIPELINE (Chinh truc tiep o day)\n",
        "# ==========================================\n",
        "SETTINGS = {\n",
        "    \"yolo.model_name\": \"yolo26x.pt\",          # yolo26n.pt (nhe) | yolo26l.pt | yolo26x.pt (nang)\n",
        "    \"yolo.tracker\": \"iou\",                    # iou: nhe, on dinh\n",
        "    \"runtime.num_workers\": 4,                 # Kaggle T4 x2: dung 4 worker\n",
        "    \"yolo.batch_size\": 32,                    # T4 16GB: batch 32 la sweet spot\n",
        "    \"yolo.conf_threshold\": 0.2,               # Nguong tin cay bbox\n",
        "    \"yolo.iou_threshold\": 0.7,                # Nguong IoU NMS\n",
        "    \"detection.retry.max_retries\": 2,         # So lan thu lai khi miss person\n",
        "    \"detection.retry.imgsz_retry\": 1280,      # Retry 1: zoom in anh\n",
        "    \"detection.retry.tta\": False,             # Tat TTA de giu VRAM\n",
        "    \"detection.retry.clahe_on_retry\": True,   # Retry 2: tang tuong phan\n",
        "    \"chunk.max_actions_per_chunk\": 5,         # So action toi da moi chunk\n",
        "    # --- TSU Specific Config ---\n",
        "    \"tsu.video_ext\": \".mp4\",\n",
        "    \"tsu.has_header\": True,\n",
        "    \"tsu.event_column\": 0,\n",
        "    \"tsu.start_column\": 1,\n",
        "    \"tsu.end_column\": 2,\n",
        "    \"tsu.event_map\": {},                      # {} = giu nguyen ten event goc\n",
        "    \"tsu.event_mapping_path\": \"event_mapping.csv\",\n",
        "}\n",
        "\n",
        "USE_DEPTH = False   # True = bat ghost legs masking (chi dung cho PKU)\n",
        "START = 0\n",
        "END = None          # None nghia la chay toi het danh sach video"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "f5g6h7i8",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 5: Kiem tra disk space Kaggle truoc khi chay\n",
        "import shutil, os\n",
        "\n",
        "total, used, free = shutil.disk_usage(\"/kaggle/working\")\n",
        "print(f\"Disk /kaggle/working: Total={total//1e9:.1f}GB | Used={used//1e9:.1f}GB | Free={free//1e9:.1f}GB\")\n",
        "if free < 3 * 1e9:\n",
        "    print(\"[WARN] Sap het disk! Xoa bo cache cu neu co.\")\n",
        "    !rm -rf /kaggle/working/outputs_detection/__pycache__\n",
        "\n",
        "os.makedirs(LOCAL_OUTPUT, exist_ok=True)\n",
        "print(f\"Local output dir: {LOCAL_OUTPUT}\")\n",
        "\n",
        "# Kiem tra doc duoc data tu Drive chua\n",
        "paths = PKU_PATHS if DATASET == \"PKU\" else TSU_PATHS\n",
        "video_dir = paths[\"video_dir\"]\n",
        "ann_dir   = paths[\"annotation_dir\"]\n",
        "\n",
        "assert os.path.isdir(video_dir), f\"Khong tim thay video_dir: {video_dir}\"\n",
        "assert os.path.isdir(ann_dir),   f\"Khong tim thay annotation_dir: {ann_dir}\"\n",
        "\n",
        "videos = sorted(os.listdir(video_dir))\n",
        "TOTAL_VIDEOS = len(videos)\n",
        "if END is None or END > TOTAL_VIDEOS:\n",
        "    END = TOTAL_VIDEOS\n",
        "print(f\"[{DATASET}] Tim thay {TOTAL_VIDEOS} files. Chay tu {START} den {END}\")\n",
        "print(f\"3 file dau: {videos[:3]}\")\n",
        "print(f\"[OK] Tat ca path hop le, san sang chay pipeline!\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "g6h7i8j9",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 6: (Tuy chon) Setup Kaggle session keepalive\n",
        "# Kaggle tu dong ngat ket noi sau ~1h khong co tuong tac.\n",
        "# Script nay in tien trinh dinh ky de Kaggle biet session van hoat dong.\n",
        "import threading, time, datetime\n",
        "\n",
        "_keepalive_stop = threading.Event()\n",
        "\n",
        "def _keepalive_worker(interval_min=10):\n",
        "    while not _keepalive_stop.wait(interval_min * 60):\n",
        "        ts = datetime.datetime.now().strftime(\"%H:%M:%S\")\n",
        "        # In ra de Kaggle biet session con hoat dong\n",
        "        output_files = []\n",
        "        import os\n",
        "        for root, _, files in os.walk(LOCAL_OUTPUT):\n",
        "            output_files.extend(files)\n",
        "        print(f\"[{ts}] Keepalive ping | Output files: {len(output_files)}\", flush=True)\n",
        "\n",
        "_keepalive_thread = threading.Thread(target=_keepalive_worker, daemon=True)\n",
        "_keepalive_thread.start()\n",
        "print(\"[OK] Keepalive thread da khoi dong (ping moi 10 phut)\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "h7i8j9k0",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 7: Nap config, ghi de path va settings\n",
        "from src.config_manager import ConfigManager\n",
        "\n",
        "cfg = ConfigManager(\"config.yaml\")\n",
        "cfg.set(\"dataset\", DATASET)\n",
        "\n",
        "paths = PKU_PATHS if DATASET == \"PKU\" else TSU_PATHS\n",
        "for k, v in paths.items():\n",
        "    cfg.set(f\"paths.{k}\", v)\n",
        "\n",
        "# Output ra LOCAL /kaggle/working/ (KHONG ghi thang len Drive)\n",
        "cfg.set(\"detection.output_dir\", LOCAL_OUTPUT)\n",
        "cfg.set(\"paths.depth_dir\", DEPTH_PATHS[DATASET])\n",
        "cfg.set(\"depth.enabled\", USE_DEPTH)\n",
        "\n",
        "for k, v in SETTINGS.items():\n",
        "    cfg.set(k, v)\n",
        "\n",
        "cfg.save(\"config.runtime.yaml\")\n",
        "print(cfg.as_dict())"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "i8j9k0l1",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 8: Chay pipeline ho tro 2 GPU (Kaggle 2xT4)\n",
        "import torch\n",
        "import multiprocessing as mp\n",
        "import os\n",
        "from src.config_manager import ConfigManager\n",
        "from src.detection_pipeline import DetectionPipeline\n",
        "\n",
        "def run_worker(gpu_id, start_idx, end_idx):\n",
        "    # Set CUDA_VISIBLE_DEVICES de co lap GPU cho worker nay\n",
        "    os.environ[\"CUDA_VISIBLE_DEVICES\"] = str(gpu_id)\n",
        "    print(f\"\\n[Worker GPU {gpu_id}] Khoi dong, xu ly video index tu {start_idx} den {end_idx}\")\n",
        "    \n",
        "    # Reload config de ap dung cac thiet lap da luu\n",
        "    cfg_worker = ConfigManager(\"config.runtime.yaml\")\n",
        "    orch = DetectionPipeline(cfg=cfg_worker)\n",
        "    orch.run_batch(start=start_idx, end=end_idx)\n",
        "\n",
        "num_gpus = torch.cuda.device_count()\n",
        "print(f\"[He thong] Phat hien {num_gpus} GPUs.\")\n",
        "\n",
        "if num_gpus > 1:\n",
        "    total_to_process = END - START\n",
        "    # Fallback cho viec chia le: GPU 0 se nhieu hon 1 video neu so luong la so le\n",
        "    mid = START + (total_to_process + 1) // 2\n",
        "    \n",
        "    print(f\"[He thong] Chia tai: GPU 0 ({START} -> {mid}), GPU 1 ({mid} -> {END})\")\n",
        "    mp.set_start_method('spawn', force=True) # Bat buoc dung spawn cho CUDA\n",
        "    \n",
        "    p0 = mp.Process(target=run_worker, args=(0, START, mid))\n",
        "    p1 = mp.Process(target=run_worker, args=(1, mid, END))\n",
        "    \n",
        "    p0.start()\n",
        "    p1.start()\n",
        "    \n",
        "    p0.join()\n",
        "    p1.join()\n",
        "    print(\"\\n[He thong] Ca 2 workers tren 2 GPU da hoan thanh!\")\n",
        "else:\n",
        "    print(\"\\n[He thong] Chi co 1 GPU (hoac khong co GPU), chay tren 1 luong...\")\n",
        "    run_worker(0, START, END)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "id": "j9k0l1m2",
      "metadata": {},
      "outputs": [],
      "source": [
        "# Cell 9: Sync output tu /kaggle/working/ len Google Drive\n",
        "# Chay sau khi pipeline hoan tat (hoac bat cu luc nao muon backup)\n",
        "# rclone copy: chi copy file moi/thay doi (khong xoa file cu tren Drive)\n",
        "import subprocess, datetime\n",
        "\n",
        "# Dung keepalive thread\n",
        "_keepalive_stop.set()\n",
        "print(f\"[{datetime.datetime.now().strftime('%H:%M:%S')}] Bat dau sync len Drive...\")\n",
        "\n",
        "result = subprocess.run([\n",
        "    \"rclone\", \"copy\",\n",
        "    LOCAL_OUTPUT,\n",
        "    \"gdrive:\" + DRIVE_OUTPUT.replace(DRIVE_ROOT + \"/\", \"MyDrive/\"),\n",
        "    \"--transfers\", \"8\",\n",
        "    \"--drive-chunk-size\", \"128M\",\n",
        "    \"--progress\",\n",
        "    \"--log-level\", \"INFO\"\n",
        "], capture_output=False, text=True)\n",
        "\n",
        "if result.returncode == 0:\n",
        "    print(f\"[{datetime.datetime.now().strftime('%H:%M:%S')}] Sync thanh cong len Drive!\")\n",
        "else:\n",
        "    print(f\"[LOI] rclone exit code: {result.returncode}\")\n",
        "\n",
        "# Kiem tra nhanh ket qua\n",
        "import os\n",
        "all_files = []\n",
        "for root, _, files in os.walk(LOCAL_OUTPUT):\n",
        "    all_files.extend(files)\n",
        "print(f\"Tong so file da tao: {len(all_files)}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "id": "k0l1m2n3",
      "metadata": {},
      "source": [
        "## Ghi chu toi uu I/O cho Kaggle\n",
        "\n",
        "| Dac diem Kaggle | Cach xu ly |\n",
        "|---|---|\n",
        "| **rclone chua co san** | Cell 2 tu dong cai qua `curl` |\n",
        "| **Khong co browser** | Dung headless token qua Kaggle Secrets |\n",
        "| **Gioi han 12 tieng/session** | Keepalive thread ping moi 10 phut |\n",
        "| **Disk /kaggle/working/ = 20GB** | Ghi output local (jsonl nhe ~100MB/session); video KHONG tai ve |\n",
        "| **Internet On bat buoc** | Phai bat trong Kaggle Settings > Internet |\n",
        "| **`--vfs-cache-max-size 15G`** | Giu 5GB cho output + overhead |\n",
        "| **Sync cuoi session** | Tranh nghẽn network khi 4 worker ghi dong thoi |"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}

nb_path = r"d:\Downloads\ĐATN\Skeleton-EAA-Pose\notebooks\extract_skeleton_kaggle.ipynb"
with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
print("Da tao file:", nb_path)
