"""
eaa_pose.run_pose
=================
Module 2 — RGB-to-3D-25-joint pose estimation pipeline.

Flow
----
For each video:

1. Load all action segments from the dataset adapter.
2. Load the per-frame track timeline generated by ``run_tracks``.
3. Open the video and process frame-by-frame:
   a. Read the selected person bbox from the track timeline.
   b. Estimate 3-D whole-body keypoints with RTMW3D (133 pts).
   c. Map 133 → NTU-120 25 joints.
   d. Accumulate into a full-video sequence ``(T, M, 25, 6)``.
4. Apply quality control (confidence filter, gap interpolation, smoothing,
   normalization) on the full sequence.
5. Slice the QC'd sequence by each segment's [start_frame, end_frame].
6. Save coordinates as SkateFormer-style ``(3, T, 25, M)`` arrays named
   ``<out_dir>/<video_name>_act<seg_id>_<label_id>.npy``.
7. Write ``metadata.json``, one QC report per video, and ``pose_stats.json``.

CLI usage
---------
    # Colab GPU (PKU v1 — after Module 1 has been run)
    python -m eaa_pose.run_pose --config configs/pku_v1.yaml --device cuda

    # Colab GPU (TSU)
    python -m eaa_pose.run_pose --config configs/tsu.yaml --device cuda

    # Local CPU smoke test (dry-run — no mmpose needed)
    python -m eaa_pose.run_pose --config configs/pku_v1.yaml \\
        --dry-run --smoke --max-videos 2 --max-frames 150 \\
        --out-dir data/samples_out
"""

from __future__ import annotations

import argparse
import warnings
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from tqdm import tqdm

from .config import PipelineConfig
from .datasets.base import ActionSegment, VideoEntry
from .datasets.pku import PKUDataset
from .datasets.tsu import TSUDataset
from .io.sample_writer import SampleWriter
from .pose.estimator_rtmw3d import PoseResult, RTMW3DEstimator
from .pose.mapping_25 import NTU25Mapper
from .pose.quality_control import SkeletonQC
from .pose.tracker import TrackedPerson
from .track_io import (
    STATUS_MULTIPLE_PERSON_CANDIDATES,
    STATUS_NO_DETECTION,
    STATUS_OK,
    STATUS_OUTSIDE_ACTION,
    STATUS_READ_FAILED,
    STATUS_TRACK_LOST,
    STATUS_UNREAD,
    read_json,
    track_path,
)


# Number of channels per joint: [x, y, z, confidence, valid_mask, reconstructed_flag]
_N_CHANNELS = 6

_FRAME_OK = STATUS_OK
_FRAME_NO_DETECTION = STATUS_NO_DETECTION
_FRAME_TRACK_LOST = STATUS_TRACK_LOST
_FRAME_POSE_FAILED = "pose_failed"
_FRAME_UNREAD = STATUS_UNREAD


class _MockEstimator:
    """Returns synthetic random 133-keypoint output (no model needed).

    Keypoint xyz values are small Gaussian noise around zero.
    Confidence values are uniformly high (0.85–1.0) to pass QC thresholds.
    """

    N_KEYPOINTS = 133

    def estimate(
        self,
        frame: np.ndarray,
        tracked_persons: list[TrackedPerson],
    ) -> list[PoseResult]:
        results: list[PoseResult] = []
        for person in tracked_persons:
            kps = np.zeros((self.N_KEYPOINTS, 4), dtype=np.float32)
            kps[:, :3] = np.random.randn(self.N_KEYPOINTS, 3).astype(np.float32) * 0.1
            kps[:, 3] = np.random.uniform(0.85, 1.0, self.N_KEYPOINTS).astype(np.float32)
            results.append(
                PoseResult(
                    track_id=person.track_id,
                    keypoints=kps,
                    bbox=person.bbox,
                )
            )
        return results


class PosePipeline:
    """Full RGB-to-3D-25-joint pose pipeline.

    Parameters
    ----------
    cfg:
        Loaded :class:`~eaa_pose.config.PipelineConfig`.  The pipeline
        reads the following config keys:

        ``detector.*``, ``tracker.*``, ``estimator.*``,
        ``quality_control.*``, ``mapping.*``, ``output.*``,
        ``video_dir``, ``segments_dir``, ``actions_xlsx``,
        ``out_dir``, ``dataset``, ``video_ext``, ``annotation``,
        ``smoke``, ``max_videos``, ``max_frames``, ``dry_run``.

    Notes
    -----
    When ``dry_run=True`` (via ``--dry-run`` CLI flag), the pipeline
    substitutes mock detector, tracker, and estimator so that the full
    pipeline flow can be tested locally without installing mmpose/mmdet.
    """

    def __init__(self, cfg: PipelineConfig) -> None:
        self._cfg     = cfg
        self._dry_run = bool(cfg.get("dry_run", False))

        # Components built lazily to avoid MMPose import on CPU-only machines.
        # In dry_run mode, mock implementations are used instead.
        self._estimator: object | None = None
        self._mapper:    NTU25Mapper = NTU25Mapper()
        self._qc:        SkeletonQC  = self._build_qc()
        self._writer:    SampleWriter | None = None
        self._metadata_videos: list[dict] = []
        self._missing_track_videos: list[str] = []
        self._pose_failed_videos: dict[str, set[int]] = {}
        self._videos_needing_review: list[dict] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> None:
        """Execute the full pipeline over the dataset."""
        cfg = self._cfg
        dataset = self._load_dataset()
        entries = dataset.load()

        mode_tag = "[dry-run]" if self._dry_run else "[gpu]"

        # Smoke-test mode: limit the number of videos processed
        is_smoke   = cfg.get("smoke", False)
        max_videos = int(cfg.get("max_videos", len(entries)) or len(entries))
        if is_smoke:
            entries = entries[:max_videos]
            print(f"{mode_tag}[smoke] Processing {len(entries)} video(s)")

        out_dir = Path(cfg["out_dir"])
        self._writer = SampleWriter(
            out_dir,
            dtype=str(cfg.get("output.dtype", "float32")),
        )
        self._metadata_videos = []
        self._missing_track_videos = []
        self._pose_failed_videos = {}
        self._videos_needing_review = []

        n_saved = 0
        for entry in tqdm(entries, desc="Videos", unit="vid"):
            try:
                n_saved += self._process_video(entry)
            except Exception as exc:  # noqa: BLE001
                warnings.warn(f"Failed on '{entry.video_id}': {exc}", stacklevel=2)

        self._write_dataset_metadata()
        self._write_pose_stats(n_saved)
        print(f"\nDone. Saved {n_saved} sample .npy files → {out_dir}")

    # ------------------------------------------------------------------
    # Per-video processing
    # ------------------------------------------------------------------

    def _process_video(self, entry: VideoEntry) -> int:
        """Process one video end-to-end. Returns number of samples saved."""
        cfg       = self._cfg
        max_frames = int(cfg.get("max_frames", 0) or 0)
        num_persons = int(cfg.get("output.num_persons", 1))
        tracks_dir = str(cfg.get("tracking.tracks_dir", "tracks"))
        tracks_path = track_path(cfg["out_dir"], tracks_dir, entry.video_id)
        if not tracks_path.exists():
            self._missing_track_videos.append(entry.video_id)
            warnings.warn(
                f"Missing track file for '{entry.video_id}': {tracks_path}",
                stacklevel=2,
            )
            return 0

        track_timeline = read_json(tracks_path)
        track_frames = track_timeline.get("frames", [])
        if not isinstance(track_frames, list):
            raise ValueError(f"Invalid track frames in {tracks_path}")

        # --- 1. Open video -----------------------------------------------
        cap = cv2.VideoCapture(str(entry.video_path))
        if not cap.isOpened():
            warnings.warn(f"Cannot open video: {entry.video_path}", stacklevel=2)
            return 0

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if max_frames > 0:
            total_frames = min(total_frames, max_frames)
        total_frames = min(total_frames, len(track_frames))

        # --- 2. Initialise per-video buffers -----------------------------
        # full_seq: (T, M, 25, 6) — filled as we read frames
        full_seq = np.zeros((total_frames, num_persons, 25, _N_CHANNELS), dtype=np.float32)
        full_seq[..., 4] = 1.0   # valid_mask default = 1 (will be corrected by QC)
        frame_statuses = [_FRAME_UNREAD for _ in range(total_frames)]

        # --- 3. Frame-by-frame pose extraction ---------------------------
        actual_frames = 0
        for frame_idx in range(total_frames):
            ret, frame = cap.read()
            if not ret:
                frame_statuses[frame_idx] = STATUS_READ_FAILED
                break
            actual_frames += 1

            frame_record = track_frames[frame_idx]
            track_status = str(frame_record.get("status", STATUS_UNREAD))
            bbox = frame_record.get("bbox")

            if track_status == STATUS_NO_DETECTION:
                full_seq[frame_idx, :, :, 4] = 0.0
                frame_statuses[frame_idx] = _FRAME_NO_DETECTION
                continue
            if track_status in (STATUS_TRACK_LOST, STATUS_READ_FAILED, STATUS_UNREAD):
                full_seq[frame_idx, :, :, 4] = 0.0
                frame_statuses[frame_idx] = track_status
                continue
            if bbox is None:
                full_seq[frame_idx, :, :, 4] = 0.0
                frame_statuses[frame_idx] = track_status
                continue

            tracked = [
                TrackedPerson(
                    track_id=int(frame_record.get("track_id") or 0),
                    bbox=np.asarray(bbox, dtype=np.float32),
                    score=float(frame_record.get("score") or 0.0),
                )
            ][:num_persons]

            pose_results = self._get_estimator().estimate(frame, tracked)
            if not pose_results:
                full_seq[frame_idx, :, :, 4] = 0.0
                frame_statuses[frame_idx] = _FRAME_POSE_FAILED
                self._record_pose_failure(entry.video_id, frame_record)
                continue

            frame_statuses[frame_idx] = (
                STATUS_MULTIPLE_PERSON_CANDIDATES
                if track_status == STATUS_MULTIPLE_PERSON_CANDIDATES
                else _FRAME_OK
            )

            for person_idx, pr in enumerate(pose_results[:num_persons]):
                kp_133 = pr.keypoints           # (133, 4)
                kp_25  = self._mapper.map(kp_133)  # (25, 4)

                # Fill [x, y, z, conf] channels
                full_seq[frame_idx, person_idx, :, :4] = kp_25
                # valid_mask: 1 if confidence > 0 else 0
                full_seq[frame_idx, person_idx, :, 4] = (kp_25[:, 3] > 0).astype(np.float32)
                # reconstructed_flag: 0 (will be updated by QC)
                full_seq[frame_idx, person_idx, :, 5] = 0.0

        cap.release()

        if actual_frames == 0:
            return 0

        # Trim to actual length
        full_seq = full_seq[:actual_frames]
        frame_statuses = frame_statuses[:actual_frames]

        # --- 4. Quality control on full sequence -------------------------
        full_seq = self._qc.process(full_seq, frame_statuses=frame_statuses)
        self._write_video_qc_report(entry, full_seq, frame_statuses, actual_frames)

        # --- 5. Slice and save per-segment -------------------------------
        n_saved = 0
        video_samples: list[dict] = []
        for seg in entry.segments:
            bounds = self._segment_bounds(seg, actual_frames)
            if bounds is None:
                continue
            start, end = bounds
            seg_array = full_seq[start : end + 1]
            sample_path = self._writer.write(seg_array, entry.video_id, seg.seg_id, seg.label_id)
            video_samples.append(
                self._sample_metadata(
                    seg=seg,
                    array=seg_array,
                    sample_path=sample_path,
                )
            )
            n_saved += 1

        self._metadata_videos.append(
            {
                "video_id": entry.video_id,
                "num_samples": len(video_samples),
                "samples": video_samples,
            }
        )

        return n_saved

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _slice_segment(
        self,
        full_seq: np.ndarray,
        seg: ActionSegment,
        total_frames: int,
    ) -> np.ndarray | None:
        """Extract a segment slice from the full video sequence.

        PKU/TSU annotations use 1-based frame indices.  We convert to
        0-based for array indexing.

        Parameters
        ----------
        full_seq:
            Full-video skeleton array of shape ``(T, M, 25, 6)``.
        seg:
            The action segment descriptor.
        total_frames:
            Actual number of frames in ``full_seq``.

        Returns
        -------
        Slice array of shape ``(seg_len, M, 25, 6)``, or None if the
        segment is out of bounds or empty.
        """
        bounds = self._segment_bounds(seg, total_frames)
        if bounds is None:
            return None
        start, end = bounds

        segment_array = full_seq[start : end + 1]   # (T_seg, M, 25, 6)
        if segment_array.shape[0] == 0:
            return None

        return segment_array

    @staticmethod
    def _segment_bounds(
        seg: ActionSegment,
        total_frames: int,
    ) -> tuple[int, int] | None:
        """Return inclusive 0-based [start, end] bounds for a segment."""
        start = max(0, seg.start_frame - 1)
        end = min(seg.end_frame - 1, total_frames - 1)
        if end < start:
            return None
        return start, end

    def _sample_metadata(
        self,
        seg: ActionSegment,
        array: np.ndarray,
        sample_path: Path,
    ) -> dict:
        """Build training metadata for one saved sample."""
        T = array.shape[0]
        return {
            "file": sample_path.name,
            "seg_id": int(seg.seg_id),
            "label_id": int(seg.label_id),
            "label_name": seg.label_name,
            "start_frame": int(seg.start_frame),
            "end_frame": int(seg.end_frame),
            "num_frames": int(T),
        }

    def _write_video_qc_report(
        self,
        entry: VideoEntry,
        full_seq: np.ndarray,
        frame_statuses: list[str],
        actual_frames: int,
    ) -> None:
        """Write one QC report JSON for this video."""
        if self._writer is None:
            return
        if not bool(self._cfg.get("qc_report.enabled", True)):
            return

        long_gap_threshold = int(
            self._cfg.get(
                "qc_report.long_gap_threshold",
                self._cfg.get("quality_control.max_interp_gap", 10),
            )
        )

        segment_reports: list[dict] = []
        for seg in entry.segments:
            bounds = self._segment_bounds(seg, actual_frames)
            if bounds is None:
                continue
            start, end = bounds
            seg_array = full_seq[start : end + 1]
            segment_reports.append(
                {
                    "seg_id": int(seg.seg_id),
                    "label_id": int(seg.label_id),
                    "label_name": seg.label_name,
                    "start_frame": int(seg.start_frame),
                    "end_frame": int(seg.end_frame),
                    "quality": self._qc.summarize(
                        seg_array,
                        frame_statuses=frame_statuses[start : end + 1],
                        long_gap_threshold=long_gap_threshold,
                        include_frame_statuses=bool(
                            self._cfg.get("qc_report.include_frame_statuses", False)
                        ),
                    ),
                }
            )

        action_mask = self._action_frame_mask(entry.segments, actual_frames)
        ignored_outside_counts: dict[str, int] = {}
        for idx, status in enumerate(frame_statuses):
            if idx < len(action_mask) and action_mask[idx]:
                continue
            if status == _FRAME_OK:
                continue
            ignored_outside_counts[status] = ignored_outside_counts.get(status, 0) + 1

        segments_needing_review = [
            int(report["seg_id"])
            for report in segment_reports
            if bool(report["quality"].get("needs_review", False))
        ]
        action_status_counts: dict[str, int] = {}
        total_action_frames = 0
        for report in segment_reports:
            total_action_frames += int(report["quality"].get("num_frames", 0))
            for status, count in report["quality"].get("frame_status_counts", {}).items():
                action_status_counts[status] = action_status_counts.get(status, 0) + int(count)

        metadata = {
            "video_id": entry.video_id,
            "num_frames": int(actual_frames),
            "quality": {
                "scope": "action_segments_only",
                "num_action_frames": int(total_action_frames),
                "frame_status_counts": action_status_counts,
                "segments_needing_review": segments_needing_review,
                "needs_review": bool(segments_needing_review),
            },
            "ignored_outside_action_status_counts": ignored_outside_counts,
            "segments": segment_reports,
        }
        self._record_video_review(entry.video_id, segment_reports)
        filename = str(self._cfg.get("qc_report.filename_template", "qc/{video_id}_qc.json"))
        filename = filename.format(video_id=entry.video_id)
        self._writer.write_metadata(metadata, filename=filename, overwrite=True)

    @classmethod
    def _action_frame_mask(
        cls,
        segments: tuple[ActionSegment, ...],
        total_frames: int,
    ) -> np.ndarray:
        """Return True for frames covered by at least one action segment."""
        mask = np.zeros(total_frames, dtype=bool)
        for seg in segments:
            bounds = cls._segment_bounds(seg, total_frames)
            if bounds is None:
                continue
            start, end = bounds
            mask[start : end + 1] = True
        return mask

    def _write_dataset_metadata(self) -> None:
        """Write one training metadata file for all saved samples."""
        if self._writer is None:
            return

        metadata = {
            "num_videos": len(self._metadata_videos),
            "num_samples": sum(v["num_samples"] for v in self._metadata_videos),
            "videos": self._metadata_videos,
        }
        filename = str(self._cfg.get("metadata.filename", "metadata.json"))
        self._writer.write_metadata(metadata, filename=filename, overwrite=True)

    def _record_pose_failure(self, video_id: str, frame_record: dict[str, Any]) -> None:
        """Track pose-failed segments for pose_stats.json."""
        seg_ids = frame_record.get("seg_ids", [])
        bucket = self._pose_failed_videos.setdefault(video_id, set())
        for seg_id in seg_ids:
            bucket.add(int(seg_id))

    def _record_video_review(self, video_id: str, segment_reports: list[dict]) -> None:
        """Track segments needing review for pose_stats.json."""
        reasons_by_segment: dict[int, set[str]] = {}
        for report in segment_reports:
            quality = report.get("quality", {})
            if not quality.get("needs_review", False):
                continue
            seg_id = int(report["seg_id"])
            reasons = reasons_by_segment.setdefault(seg_id, set())
            if int(quality.get("longest_joint_invalid_gap", 0)) > int(
                quality.get("long_gap_threshold", 0)
            ):
                reasons.add("long_invalid_gap")
            if float(quality.get("high_missing_frame_ratio", 0.0)) > 0:
                reasons.add("high_missing_ratio")
            if float(quality.get("full_body_missing_ratio", 0.0)) > 0:
                reasons.add("full_body_missing")
            if not reasons:
                reasons.add("needs_review")

        if not reasons_by_segment:
            return
        all_reasons = sorted({r for reasons in reasons_by_segment.values() for r in reasons})
        self._videos_needing_review.append(
            {
                "video_id": video_id,
                "segments": sorted(reasons_by_segment),
                "reasons": all_reasons,
            }
        )

    def _write_pose_stats(self, n_saved: int) -> None:
        """Write dataset-level Step 2B pose statistics."""
        if self._writer is None:
            return
        pose_failed_videos = [
            {"video_id": video_id, "segments": sorted(seg_ids)}
            for video_id, seg_ids in sorted(self._pose_failed_videos.items())
        ]
        payload = {
            "num_videos": len(self._metadata_videos),
            "num_samples": int(n_saved),
            "missing_track_videos": sorted(self._missing_track_videos),
            "pose_failed_videos": pose_failed_videos,
            "videos_needing_review": self._videos_needing_review,
        }
        filename = str(self._cfg.get("pose_stats.filename", "pose_stats.json"))
        self._writer.write_metadata(payload, filename=filename, overwrite=True)

    def _load_dataset(self):
        """Instantiate the correct dataset adapter from config."""
        cfg        = self._cfg
        dataset_id = cfg.get("dataset", "pku_v1")
        video_ext  = cfg.get("video_ext", ".avi")

        if dataset_id in ("pku_v1", "pku_v2"):
            return PKUDataset(
                video_dir    = cfg["video_dir"],
                segments_dir = cfg["segments_dir"],
                actions_xlsx = cfg["actions_xlsx"],
                video_ext    = video_ext,
            )
        elif dataset_id == "tsu":
            return TSUDataset(
                video_dir    = cfg["video_dir"],
                segments_dir = cfg["segments_dir"],
                video_ext    = video_ext,
            )
        else:
            raise ValueError(f"Unknown dataset '{dataset_id}' in config.")

    def _get_estimator(self) -> object:
        """Return the estimator (real or mock), building it lazily on first access."""
        if self._estimator is None:
            self._estimator = _MockEstimator() if self._dry_run else self._build_estimator()
        return self._estimator

    def _build_estimator(self) -> RTMW3DEstimator:
        cfg = self._cfg
        # Inherit device from detector if estimator.device is not set separately.
        device = cfg.get("estimator.device", cfg.get("detector.device", "cuda"))
        return RTMW3DEstimator(
            config                 = cfg["estimator.config"],
            checkpoint             = cfg["estimator.checkpoint"],
            device                 = device,
            keypoint_conf_threshold= float(cfg.get("estimator.keypoint_conf_threshold", 0.3)),
        )

    def _build_qc(self) -> SkeletonQC:
        cfg = self._cfg
        return SkeletonQC(
            min_conf          = float(cfg.get("quality_control.min_conf",          0.3)),
            max_missing_ratio = float(cfg.get("quality_control.max_missing_ratio", 0.4)),
            max_interp_gap    = int(cfg.get("quality_control.max_interp_gap",   10)),
            smooth_window     = int(cfg.get("quality_control.smooth_window",      5)),
            smooth_polyorder  = int(cfg.get("quality_control.smooth_polyorder",   2)),
            normalize         = bool(cfg.get("quality_control.normalize",       True)),
        )


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run the RGB-to-3D-25-joint pose pipeline.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--config", required=True,
        help="Dataset config YAML (e.g. configs/pku_v1.yaml).",
    )
    # Optional overrides
    p.add_argument("--video-dir",    dest="video_dir",    default=None)
    p.add_argument("--segments-dir", dest="segments_dir", default=None)
    p.add_argument("--actions-xlsx", dest="actions_xlsx", default=None)
    p.add_argument("--out-dir",      dest="out_dir",      default=None)
    p.add_argument(
        "--device", dest="device", default=None,
        help="Torch device: 'cuda' or 'cpu'.",
    )
    p.add_argument(
        "--num-persons", dest="num_persons", type=int, default=None,
        help="Number of persons to track per frame.",
    )
    p.add_argument(
        "--smoke", dest="smoke", action="store_true", default=None,
        help="Smoke-test mode: process only --max-videos videos.",
    )
    p.add_argument(
        "--max-videos", dest="max_videos", type=int, default=None,
        help="(smoke) Max number of videos to process.",
    )
    p.add_argument(
        "--max-frames", dest="max_frames", type=int, default=None,
        help="(smoke) Max frames per video.",
    )
    p.add_argument(
        "--dry-run", dest="dry_run", action="store_true", default=None,
        help=(
            "Dry-run mode: use mock detector/tracker/estimator. "
            "No mmpose/mmdet needed. Useful for local pipeline testing."
        ),
    )
    return p


def main() -> None:
    parser = _build_parser()
    args   = parser.parse_args()
    cfg    = PipelineConfig.load(args.config, cli_args=args)
    PosePipeline(cfg).run()


if __name__ == "__main__":
    main()
